### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rijotech** [bogeta11040/if-youtube-channel-live#1]
It doesn't work.
![image](https://user-images.githubusercontent.com/17016357/206919632-ae628739-c982-4ebb-9a03-d0b24369d1d1.png)

**Comment by WisdomIT** [comment]
You should use this code on node.js.
otherwise, it's unavailable to fetch because of CORS policy.

**Comment by bogeta11040** [comment]
Confirming @WisdomIT comment and therefore I'm changing the status of this issue to closed.

Regards,
Igor
